version: '3.8'

services:
  saaguvalgus-app:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    container_name: saaguvalgus_web
    restart: unless-stopped
    ports:
      - "3002:80"
    environment:
      - NODE_ENV=production

