version: '3.8'

services:
  saaguvalgus-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: saaguvalgus-web:latest
    container_name: saaguvalgus_web
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
